import"./assets/styles-DmH0OdqC.js";import{a as r}from"./assets/vendor-N5iQpiFS.js";const u="https://dummyjson.com/",a={allProducts:"products",allCategory:"products/category-list",productsByCategory:"products/category",productByName:"products/search"},l=12;r.defaults.baseURL=u;const p=async()=>(await r.get(a.allCategory)).data,d=async t=>(await r.get(a.allProducts,{params:{limit:l,skip:(t-1)*l}})).data,m=async t=>(await r.get(`${a.productsByCategory}/${t}`)).data,y=async t=>(await r.get(`${a.allProducts}/${t}`)).data,g=async t=>(await r.get(a.productByName,{params:{q:t}})).data,e={categoryList:document.querySelector(".categories"),productsList:document.querySelector(".products"),divModal:document.querySelector(".modal"),divModalContent:document.querySelector(".modal-product"),closeModalBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),clearBtn:document.querySelector(".search-form__btn-clear"),input:document.querySelector(".search-form__input")},_=t=>{const o=t.map(c=>`<li class="categories__item"><button class="categories__btn" type="button">${c}</button></li>`).join("");e.categoryList.innerHTML=o},n=t=>{const o=t.map(c=>`<li class="products__item" data-id="${c.id}">
        <img class="products__image" src="${c.thumbnail}" alt="${c.title}"/>
    <p class="products__title">${c.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${c.brand}</span></p>
    <p class="products__category">Category:${c.category}</p>
    <p class="products__price">Price: ${c.price}$</p>
 </li>`).join("");e.productsList.insertAdjacentHTML("beforeend",o)},i=()=>{e.productsList.innerHTML=""},b=t=>{const o=t.map(c=>`<img class="modal-product__img" src="${c.thumbnail}" alt="${c.title}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${c.title}</p>
        <ul class="modal-product__tags"></ul>
        <p class="modal-product__description">${c.description}</p>
        <p class="modal-product__shipping-information">Shipping:${c.shippingInformation}</p>
        <p class="modal-product__return-policy">Return Policy:${c.returnPolicy}</p>
        <p class="modal-product__price">Price:${c.price} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>
`).join("");e.divModalContent.innerHTML=o,e.divModal.classList.add("modal--is-open")},f=()=>{const t=document.querySelector(".categories__btn");t&&t.classList.add("categories__btn--active")},h=t=>{const o=document.querySelector(".categories__btn--active");o&&o.classList.remove("categories__btn--active"),t.target.classList.add("categories__btn--active")},L=()=>{document.querySelector(".not-found").classList.add("not-found--visible")},v=async t=>{try{const o=await y(t);b([o])}catch(o){console.log(o)}},B=()=>{e.divModal.classList.remove("modal--is-open")},P=async()=>{try{const t=await p();_(["All",...t]),f()}catch(t){console.log(t)}},$=async()=>{try{const t=await d(1);n(t.products)}catch(t){console.log(t)}},C=async t=>{if(t.target.nodeName!=="BUTTON")return;const o=t.target.textContent;let c=null;h(t);try{o==="All"?c=await d(1):c=await m(o),i(),n(c.products)}catch(s){console.log(s)}},S=async t=>{const o=t.target.closest(".products__item");if(!o)return;const c=o.dataset.id;v(c)},M=async t=>{t.preventDefault();const o=t.target.searchValue.value.trim();if(!o)return;const c=o.slice(0,4).toLowerCase();try{const s=await g(c);if(i(),!s.products.length){L();return}n(s.products)}catch(s){console.log(s)}},q=async()=>{e.input.value="";try{const t=await d(1);i(),n(t.products)}catch(t){console.log(t)}};P();$();e.categoryList.addEventListener("click",C);e.productsList.addEventListener("click",S);e.closeModalBtn.addEventListener("click",B);e.searchForm.addEventListener("submit",M);e.clearBtn.addEventListener("click",q);
//# sourceMappingURL=index.js.map
